# Generated by Django 4.1.7 on 2023-04-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AlterField(
            model_name='auction',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments_in_the_auction', to='auctions.comment'),
        ),
    ]
